### PR TITLE
New version for CRAN

### PR DESCRIPTION
**Pull request by pitkant**
Lots of small changes, at least compared to last CRAN release 0.7.26 from 2015. NEWS.md contains most important changes, but I'll copy paste them here as well:

# sorvi 0.8.18 (2022-05-24)

### DEPRECATED AND DEFUNCT

- Removed the following outdated .R files and related functions: `convert_municipality_codes.R`, `convert_municipality_names.R`, `get_municipality_info_mml.R`, `municipality_to_province.R` and `ropengov_storage_path.R`.
- Removed `qpdf`, `reshape2`, `RCurl` and `rjson` from Depends and `curl` from imports

### DOCUMENTATION FIXES

- Removed mentions to deprecated functions in package vignette

# sorvi 0.8.17 (2021-11-30)

### NEW FEATURES

- New function: `get_ifpi_charts()` for scraping data from Musiikkituottajat - IFPI Finland ry charts

# sorvi 0.8.16 (2021-11-25)

### NEW FEATURES

- New function: `cran_downloads()` for getting information about package downloads and optionally visualizing them
- New function: `gh_issue_stats()` for downloading information about opened issues and pull requests from different repositories

### MINOR IMPROVEMENTS

- Using GitHub Actions for testing and building pkgdown website with rogtemplate, rendering README.md file
- Overall package cleaning and fixing warnings, errors and notes

### DEPRECATED AND DEFUNCT

- Removed hetu-related functions, tests and examples in vignette (now in separate hetu-package)

### DOCUMENTATION FIXES

- Option "eval=false" in vignette examples that relied on GitHub as a data repository; GitHub seemed to deny connections when data was downloaded several times during vignette rebuilding

### CODE REVIEW

**Comment by pitkant** [comment]
As a clarification, this PR includes only changes from 0.8.17 -> 0.8.18. The changes mentioned in 0.8.17 and below are already included in the master-branch. Just wanted to give a quick view on what has changed since last release in 2015!

**Review by antagomir — APPROVED** [review]
Nice! Confirm when ready, I will then make final checks and submit.

**Comment by pitkant** [comment]
For my part it is now ready, I added a cran-comments.md template and some additional GitHub actions checks that can be run manually after PR is merged

**Comment by antagomir** [comment]
Roger!

**Pull request merged**
