### PR TITLE
Load data from GitHub

### PR DESCRIPTION
**Pull request by jlehtoma**
This is perhaps not the ideal solution, but `ropengov_storage_path()` can now be easily adjusted if new storage paths become relevant.

### CODE REVIEW

**Comment by jlehtoma** [comment]
Woah, tests are failing. Don't merge this yet.

**Comment by jlehtoma** [comment]
There we go, can be reviewed/approved now.

**Comment by antagomir** [comment]
This looks useful for now. But the idea of the OKF servers was the higher bandwidth. Is this still critical - I would wait for some comments before merging?

**Comment by jlehtoma** [comment]
My 5 cents: I wouldn't worry about the bandwidth (especially with sorvi) until we run into trouble or get a notification. Fact of the matter is, that right now the package is half-broken because OKFI servers are offline.

**Comment by antagomir** [comment]
ok fine. merged.

**Pull request merged**
